[project]
name = "uav-mcp2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "torch",
  "torchvision",
  "torchaudio",
]

[tool.uv.sources]
pytorch-cuda = { url = "https://download.pytorch.org/whl/cu121" }
